// This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.repo.deleteRecord` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    ///The NSID of the record collection.
    pub collection: String,
    ///The handle or DID of the repo.
    pub repo: String,
    ///The key of the record.
    pub rkey: String,
    ///Compare and swap with the previous commit by CID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub swap_commit: Option<String>,
    ///Compare and swap with the previous record by CID.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub swap_record: Option<String>,
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    InvalidSwap(Option<String>),
}
