// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Definitions for the `com.atproto.repo.strongRef` namespace."]
#![doc = "A URI with a content-hash fingerprint."]
#[doc = "`com.atproto.repo.strongRef`"]
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Main {
    pub cid: String,
    pub uri: String,
}
