// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.signature.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct SigDetailData {
    pub property: String,
    pub value: String,
}
pub type SigDetail = crate::types::Object<SigDetailData>;
