// This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.admin` namespace.
pub mod create_communication_template;
pub mod defs;
pub mod delete_account;
pub mod delete_communication_template;
pub mod disable_account_invites;
pub mod disable_invite_codes;
pub mod emit_moderation_event;
pub mod enable_account_invites;
pub mod get_account_info;
pub mod get_account_infos;
pub mod get_invite_codes;
pub mod get_moderation_event;
pub mod get_record;
pub mod get_repo;
pub mod get_subject_status;
pub mod list_communication_templates;
pub mod query_moderation_events;
pub mod query_moderation_statuses;
pub mod search_repos;
pub mod send_email;
pub mod update_account_email;
pub mod update_account_handle;
pub mod update_account_password;
pub mod update_communication_template;
pub mod update_subject_status;
