// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.identity` namespace.
pub mod get_recommended_did_credentials;
pub mod request_plc_operation_signature;
pub mod resolve_handle;
pub mod sign_plc_operation;
pub mod submit_plc_operation;
pub mod update_handle;
