// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.lexicon` namespace.
pub mod schema;
#[derive(Debug)]
pub struct Schema;
impl crate::types::Collection for Schema {
    const NSID: &'static str = "com.atproto.lexicon.schema";
    type Record = schema::Record;
}
