// This file is generated by atrium-codegen. DO NOT EDIT.
pub mod apply_writes;
pub mod create_record;
pub mod delete_record;
pub mod describe_repo;
pub mod get_record;
pub mod list_records;
pub mod put_record;
pub mod rebase_repo;
pub mod strong_ref;
pub mod upload_blob;
