// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.sync` namespace.
pub mod get_blob;
pub mod get_blocks;
pub mod get_checkout;
pub mod get_head;
pub mod get_latest_commit;
pub mod get_record;
pub mod get_repo;
pub mod get_repo_status;
pub mod list_blobs;
pub mod list_repos;
pub mod list_repos_by_collection;
pub mod notify_of_update;
pub mod request_crawl;
pub mod subscribe_repos;
