// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `chat` namespace.
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-chatbsky")))]
#[cfg(feature = "namespace-chatbsky")]
pub mod bsky;
