// This file is generated by atrium-codegen. DO NOT EDIT.
# ! [doc = include_str ! ("../README.md")]
pub use atrium_xrpc as xrpc;
pub mod agent;
pub mod app;
pub mod blob;
pub mod client;
pub mod com;
pub mod did_doc;
pub mod records;
