// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Implementing the traits of all XRPC requests for agent."]
impl<T> crate::app::bsky::actor::get_preferences::GetPreferences for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::get_profile::GetProfile for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::get_profiles::GetProfiles for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::get_suggestions::GetSuggestions for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::put_preferences::PutPreferences for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::search_actors::SearchActors for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::actor::search_actors_typeahead::SearchActorsTypeahead
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::app::bsky::feed::describe_feed_generator::DescribeFeedGenerator
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::app::bsky::feed::get_actor_feeds::GetActorFeeds for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_author_feed::GetAuthorFeed for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_feed::GetFeed for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_feed_generator::GetFeedGenerator for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_feed_generators::GetFeedGenerators for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_feed_skeleton::GetFeedSkeleton for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_likes::GetLikes for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_post_thread::GetPostThread for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_posts::GetPosts for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_reposted_by::GetRepostedBy for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::feed::get_timeline::GetTimeline for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_blocks::GetBlocks for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_followers::GetFollowers for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_follows::GetFollows for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_list::GetList for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_list_mutes::GetListMutes for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_lists::GetLists for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::get_mutes::GetMutes for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::mute_actor::MuteActor for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::mute_actor_list::MuteActorList for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::unmute_actor::UnmuteActor for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::graph::unmute_actor_list::UnmuteActorList for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::notification::get_unread_count::GetUnreadCount
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::app::bsky::notification::list_notifications::ListNotifications
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::app::bsky::notification::update_seen::UpdateSeen for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::unspecced::get_popular::GetPopular for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::app::bsky::unspecced::get_popular_feed_generators::GetPopularFeedGenerators
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::disable_account_invites::DisableAccountInvites
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::disable_invite_codes::DisableInviteCodes
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::enable_account_invites::EnableAccountInvites
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::get_invite_codes::GetInviteCodes for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::admin::get_moderation_action::GetModerationAction
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::get_moderation_actions::GetModerationActions
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::get_moderation_report::GetModerationReport
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::get_moderation_reports::GetModerationReports
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::get_record::GetRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::admin::get_repo::GetRepo for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::admin::rebase_repo::RebaseRepo for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::admin::resolve_moderation_reports::ResolveModerationReports
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::reverse_moderation_action::ReverseModerationAction
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::search_repos::SearchRepos for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::admin::take_moderation_action::TakeModerationAction
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::update_account_email::UpdateAccountEmail
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::admin::update_account_handle::UpdateAccountHandle
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::identity::resolve_handle::ResolveHandle for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::identity::update_handle::UpdateHandle for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::label::query_labels::QueryLabels for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::moderation::create_report::CreateReport for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::apply_writes::ApplyWrites for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::create_record::CreateRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::delete_record::DeleteRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::describe_repo::DescribeRepo for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::get_record::GetRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::list_records::ListRecords for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::put_record::PutRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::rebase_repo::RebaseRepo for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::repo::upload_blob::UploadBlob for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::create_account::CreateAccount for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::create_app_password::CreateAppPassword
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::create_invite_code::CreateInviteCode
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::create_invite_codes::CreateInviteCodes
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::create_session::CreateSession for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::delete_account::DeleteAccount for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::delete_session::DeleteSession for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::describe_server::DescribeServer for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::get_account_invite_codes::GetAccountInviteCodes
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::get_session::GetSession for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::list_app_passwords::ListAppPasswords
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::refresh_session::RefreshSession for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::request_account_delete::RequestAccountDelete
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::request_password_reset::RequestPasswordReset
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::server::reset_password::ResetPassword for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::server::revoke_app_password::RevokeAppPassword
    for crate::agent::AtpAgent<T>
where
    T: crate::xrpc::XrpcClient + Send + Sync,
{
}
impl<T> crate::com::atproto::sync::get_blob::GetBlob for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_blocks::GetBlocks for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_checkout::GetCheckout for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_commit_path::GetCommitPath for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_head::GetHead for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_record::GetRecord for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::get_repo::GetRepo for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::list_blobs::ListBlobs for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::list_repos::ListRepos for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::notify_of_update::NotifyOfUpdate for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
impl<T> crate::com::atproto::sync::request_crawl::RequestCrawl for crate::agent::AtpAgent<T> where
    T: crate::xrpc::XrpcClient + Send + Sync
{
}
