// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.getBlob` namespace.

/// Get a blob associated with a given repo.
#[async_trait::async_trait]
pub trait GetBlob: crate::xrpc::XrpcClient {
    async fn get_blob(&self, params: Parameters) -> Result<(), Box<dyn std::error::Error>> {
        let body = crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "com.atproto.sync.getBlob",
            Some(serde_urlencoded::to_string(&params)?),
            None,
            None,
        )
        .await?;
        serde_json::from_slice(&body).map_err(|e| e.into())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    /// The CID of the blob to fetch
    pub cid: String,
    /// The DID of the repo.
    pub did: String,
}


pub enum Error {
}
