// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Definitions for the `com.atproto.sync.notifyOfUpdate` namespace."]
#[doc = "`com.atproto.sync.notifyOfUpdate`"]
#[doc = "Notify a crawling service of a recent update. Often when a long break between updates causes the connection with the crawling service to break."]
#[async_trait::async_trait]
pub trait NotifyOfUpdate: crate::xrpc::XrpcClient {
    async fn notify_of_update(&self, params: Parameters) -> Result<(), Box<dyn std::error::Error>> {
        let _ = crate::xrpc::XrpcClient::send::<Error>(
            self,
            http::Method::GET,
            "com.atproto.sync.notifyOfUpdate",
            Some(serde_urlencoded::to_string(&params)?),
            None,
            None,
        )
        .await?;
        Ok(())
    }
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    #[doc = "Hostname of the service that is notifying of update."]
    pub hostname: String,
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
