// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.requestCrawl` namespace.

/// Request a service to persistently crawl hosted repos.
#[async_trait::async_trait]
pub trait RequestCrawl: crate::xrpc::XrpcClient {
    async fn request_crawl(&self, params: Parameters) -> Result<(), Box<dyn std::error::Error>> {
        crate::xrpc::XrpcClient::send_unit(
            self,
            http::Method::GET,
            "com.atproto.sync.requestCrawl",
            Some(params),
            Option::<()>::None,
        )
        .await
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    /// Hostname of the service that is requesting to be crawled.
    pub hostname: String,
}

pub enum Error {
}
