// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.disableInviteCodes` namespace.

/// Disable some set of codes and/or all codes associated with a set of users
#[async_trait::async_trait]
pub trait DisableInviteCodes: crate::xrpc::XrpcClient {
    async fn disable_invite_codes(&self, input: Input) -> Result<(), Box<dyn std::error::Error>> {
        let _ = crate::xrpc::XrpcClient::send(
            self,
            http::Method::POST,
            "com.atproto.admin.disableInviteCodes",
            None,
            Some(serde_json::to_vec(&input)?),
            Some(String::from("application/json")),
        )
        .await?;
        Ok(())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub codes: Option<Vec<String>>,
}

pub enum Error {
}
