// This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.admin.emitModerationEvent` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    pub created_by: crate::types::string::Did,
    pub event: InputEventEnum,
    pub subject: InputSubjectEnum,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subject_blob_cids: Option<Vec<crate::types::string::Cid>>,
}
pub type Output = crate::com::atproto::admin::defs::ModEventView;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    SubjectHasAction(Option<String>),
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum InputEventEnum {
    #[serde(rename = "com.atproto.admin.defs#modEventTakedown")]
    ComAtprotoAdminDefsModEventTakedown(
        Box<crate::com::atproto::admin::defs::ModEventTakedown>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventAcknowledge")]
    ComAtprotoAdminDefsModEventAcknowledge(
        Box<crate::com::atproto::admin::defs::ModEventAcknowledge>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventEscalate")]
    ComAtprotoAdminDefsModEventEscalate(
        Box<crate::com::atproto::admin::defs::ModEventEscalate>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventComment")]
    ComAtprotoAdminDefsModEventComment(
        Box<crate::com::atproto::admin::defs::ModEventComment>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventLabel")]
    ComAtprotoAdminDefsModEventLabel(
        Box<crate::com::atproto::admin::defs::ModEventLabel>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventReport")]
    ComAtprotoAdminDefsModEventReport(
        Box<crate::com::atproto::admin::defs::ModEventReport>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventMute")]
    ComAtprotoAdminDefsModEventMute(Box<crate::com::atproto::admin::defs::ModEventMute>),
    #[serde(rename = "com.atproto.admin.defs#modEventReverseTakedown")]
    ComAtprotoAdminDefsModEventReverseTakedown(
        Box<crate::com::atproto::admin::defs::ModEventReverseTakedown>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventUnmute")]
    ComAtprotoAdminDefsModEventUnmute(
        Box<crate::com::atproto::admin::defs::ModEventUnmute>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventEmail")]
    ComAtprotoAdminDefsModEventEmail(
        Box<crate::com::atproto::admin::defs::ModEventEmail>,
    ),
    #[serde(rename = "com.atproto.admin.defs#modEventTag")]
    ComAtprotoAdminDefsModEventTag(Box<crate::com::atproto::admin::defs::ModEventTag>),
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum InputSubjectEnum {
    #[serde(rename = "com.atproto.admin.defs#repoRef")]
    ComAtprotoAdminDefsRepoRef(Box<crate::com::atproto::admin::defs::RepoRef>),
    #[serde(rename = "com.atproto.repo.strongRef")]
    ComAtprotoRepoStrongRefMain(Box<crate::com::atproto::repo::strong_ref::Main>),
}
