// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.getModerationReport` namespace.

/// View details about a moderation report.
#[async_trait::async_trait]
pub trait GetModerationReport: crate::xrpc::XrpcClient {
    async fn get_moderation_report(&self, params: Parameters) -> Result<Output, Box<dyn std::error::Error>> {
        let body = crate::xrpc::XrpcClient::send::<Error>(
            self,
            http::Method::GET,
            "com.atproto.admin.getModerationReport",
            Some(serde_urlencoded::to_string(&params)?),
            None,
            None,
        )
        .await?;
        serde_json::from_slice(&body).map_err(|e| e.into())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    pub id: i32,
}

pub type Output = crate::com::atproto::admin::defs::ReportViewDetail;

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
}
