// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.getModerationReport` namespace.

/// View details about a moderation report.
#[async_trait::async_trait]
pub trait GetModerationReport: crate::xrpc::XrpcClient {
    async fn get_moderation_report(&self, params: Parameters) -> Result<Output, Box<dyn std::error::Error>> {
        crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "com.atproto.admin.getModerationReport",
            Some(params),
            Option::<()>::None,
        )
        .await
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    pub id: i32,
}

pub type Output = crate::com::atproto::admin::defs::ReportViewDetail;

pub enum Error {
}
