// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Definitions for the `com.atproto.admin.updateAccountEmail` namespace."]
#[doc = "`com.atproto.admin.updateAccountEmail`"]
#[doc = "Administrative action to update an account's email"]
#[async_trait::async_trait]
pub trait UpdateAccountEmail: crate::xrpc::XrpcClient {
    async fn update_account_email(&self, input: Input) -> Result<(), crate::xrpc::Error<Error>> {
        let _ = crate::xrpc::XrpcClient::send(
            self,
            http::Method::POST,
            "com.atproto.admin.updateAccountEmail",
            None,
            Some(serde_json::to_vec(&input)?),
            Some(String::from("application/json")),
        )
        .await?;
        Ok(())
    }
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    #[doc = "The handle or DID of the repo."]
    pub account: String,
    pub email: String,
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
