// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.identity.updateHandle` namespace.

/// Updates the handle of the account
pub trait UpdateHandle {
    fn update_handle(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub handle: String,
}

pub enum Error {
}
