// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.notification.updateSeen` namespace.

/// Notify server that the user has seen notifications.
pub trait UpdateSeen {
    fn update_seen(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub seen_at: String,
}

pub enum Error {
}
