// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.repo.applyWrites` namespace.

// TODO

// com.atproto.repo.applyWrites#create
/// Create a new record.
pub struct Create {
    pub collection: String,
    pub rkey: Option<String>,
    // pub value: ...,
}

// com.atproto.repo.applyWrites#delete
/// Delete an existing record.
pub struct Delete {
    pub collection: String,
    pub rkey: String,
}

// com.atproto.repo.applyWrites#update
/// Update an existing record.
pub struct Update {
    pub collection: String,
    pub rkey: String,
    // pub value: ...,
}
