// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.repo.describeRepo` namespace.

/// Get information about the repo, including the list of collections.
pub trait DescribeRepo {
    fn describe_repo(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    /// The handle or DID of the repo.
    pub repo: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub collections: Vec<String>,
    pub did: String,
    // pub did_doc: ...,
    pub handle: String,
    pub handle_is_correct: bool,
}

pub enum Error {
}
