// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.repo.listRecords` namespace.

/// List a range of records in a collection.
pub trait ListRecords {
    fn list_records(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    /// The NSID of the record type.
    pub collection: String,
    pub cursor: Option<String>,
    /// The number of records to return.
    pub limit: Option<i32>,
    /// The handle or DID of the repo.
    pub repo: String,
    /// Reverse the order of the returned records?
    pub reverse: Option<bool>,
    /// DEPRECATED: The highest sort-ordered rkey to stop at (exclusive)
    pub rkey_end: Option<String>,
    /// DEPRECATED: The lowest sort-ordered rkey to start from (exclusive)
    pub rkey_start: Option<String>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub cursor: Option<String>,
    pub records: Vec<Record>,
}

pub enum Error {
}

// com.atproto.repo.listRecords#record
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Record {
    pub cid: String,
    pub uri: String,
    // pub value: ...,
}
