// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.actor.defs` namespace.

// app.bsky.actor.defs#profileView
pub struct ProfileView {
    pub avatar: Option<String>,
    pub description: Option<String>,
    pub did: String,
    pub display_name: Option<String>,
    pub handle: String,
    pub indexed_at: Option<String>,
    // pub labels: ...,
    // pub viewer: ...
}

// app.bsky.actor.defs#profileViewBasic
pub struct ProfileViewBasic {
    pub avatar: Option<String>,
    pub did: String,
    pub display_name: Option<String>,
    pub handle: String,
    // pub labels: ...,
    // pub viewer: ...
}

// app.bsky.actor.defs#profileViewDetailed
pub struct ProfileViewDetailed {
    pub avatar: Option<String>,
    pub banner: Option<String>,
    pub description: Option<String>,
    pub did: String,
    pub display_name: Option<String>,
    pub followers_count: Option<i32>,
    pub follows_count: Option<i32>,
    pub handle: String,
    pub indexed_at: Option<String>,
    // pub labels: ...,
    pub posts_count: Option<i32>,
    // pub viewer: ...
}

// app.bsky.actor.defs#viewerState
pub struct ViewerState {
    pub followed_by: Option<String>,
    pub following: Option<String>,
    pub muted: Option<bool>,
}
