// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.embed.defs` namespace.
///width:height represents an aspect ratio. It may be approximate, and may not correspond to absolute dimensions in any given unit.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct AspectRatioData {
    pub height: core::num::NonZeroU64,
    pub width: core::num::NonZeroU64,
}
pub type AspectRatio = crate::types::Object<AspectRatioData>;
