// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.getBlocks` namespace.

/// Gets blocks from a given repo.
pub trait GetBlocks {
    fn get_blocks(&self, input: Parameters) -> Result<(), Error>;
}

pub struct Parameters {
    pub cids: Vec<String>,
    /// The DID of the repo.
    pub did: String,
}


pub enum Error {
}
