// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.getRecord` namespace.

/// Gets blocks needed for existence or non-existence of record.
pub trait GetRecord {
    fn get_record(&self, input: Parameters) -> Result<(), Error>;
}

pub struct Parameters {
    pub collection: String,
    /// An optional past commit CID.
    pub commit: Option<String>,
    /// The DID of the repo.
    pub did: String,
    pub rkey: String,
}


pub enum Error {
}
