// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.getHead` namespace.

/// Gets the current HEAD CID of a repo.
pub trait GetHead {
    fn get_head(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    /// The DID of the repo.
    pub did: String,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Output {
    pub root: String,
}

pub enum Error {
}
