// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.getCommitPath` namespace.

/// Gets the path of repo commits
pub trait GetCommitPath {
    fn get_commit_path(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    /// The DID of the repo.
    pub did: String,
    /// The earliest commit to start from
    pub earliest: Option<String>,
    /// The most recent commit
    pub latest: Option<String>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub commits: Vec<String>,
}

pub enum Error {
}
