// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.listRepos` namespace.

/// List dids and root cids of hosted repos
pub trait ListRepos {
    fn list_repos(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    pub cursor: Option<String>,
    pub limit: Option<i32>,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Output {
    pub cursor: Option<String>,
    pub repos: Vec<Repo>,
}

pub enum Error {
}

// com.atproto.sync.listRepos#repo
#[derive(serde::Serialize, serde::Deserialize)]
pub struct Repo {
    pub did: String,
    pub head: String,
}
