// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.listBlobs` namespace.

/// List blob cids for some range of commits
#[async_trait::async_trait]
pub trait ListBlobs: crate::xrpc::XrpcClient {
    async fn list_blobs(&self, params: Parameters) -> Result<Output, Box<dyn std::error::Error>> {
        crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "com.atproto.sync.listBlobs",
            Some(params),
            Option::<()>::None,
        )
        .await
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    /// The DID of the repo.
    pub did: String,
    /// The earliest commit to start from
    pub earliest: Option<String>,
    /// The most recent commit
    pub latest: Option<String>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub cids: Vec<String>,
}

pub enum Error {
}
