// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.sync.requestCrawl` namespace.

/// Request a service to persistently crawl hosted repos.
pub trait RequestCrawl {
    fn request_crawl(&self, input: Parameters) -> Result<(), Error>;
}

pub struct Parameters {
    /// Hostname of the service that is requesting to be crawled.
    pub hostname: String,
}

pub enum Error {
}
