// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Definitions for the `app.bsky.unspecced.getPopularFeedGenerators` namespace."]
#[doc = "`app.bsky.unspecced.getPopularFeedGenerators`"]
#[doc = "An unspecced view of globally popular feed generators"]
#[async_trait::async_trait]
pub trait GetPopularFeedGenerators: crate::xrpc::XrpcClient {
    async fn get_popular_feed_generators(&self) -> Result<Output, crate::xrpc::Error<Error>> {
        let body = crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "app.bsky.unspecced.getPopularFeedGenerators",
            None,
            None,
            None,
        )
        .await?;
        serde_json::from_slice(&body).map_err(|e| e.into())
    }
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub feeds: Vec<crate::app::bsky::feed::defs::GeneratorView>,
}
#[derive(serde :: Serialize, serde :: Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
