// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.disableInviteCodes` namespace.

/// Disable some set of codes and/or all codes associated with a set of users
pub trait DisableInviteCodes {
    fn disable_invite_codes(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub accounts: Option<Vec<String>>,
    pub codes: Option<Vec<String>>,
}

pub enum Error {
}
