// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.reverseModerationAction` namespace.

/// Reverse a moderation action.
pub trait ReverseModerationAction {
    fn reverse_moderation_action(&self, input: Input) -> Result<Output, Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub created_by: String,
    pub id: i32,
    pub reason: String,
}

pub type Output = crate::com::atproto::admin::defs::ActionView;

pub enum Error {
}
