// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.admin.updateAccountEmail` namespace.

/// Administrative action to update an account's email
pub trait UpdateAccountEmail {
    fn update_account_email(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    /// The handle or DID of the repo.
    pub account: String,
    pub email: String,
}

pub enum Error {
}
