// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.setting.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OptionData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<crate::types::string::Datetime>,
    pub created_by: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    pub did: crate::types::string::Did,
    pub key: crate::types::string::Nsid,
    pub last_updated_by: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub manager_role: core::option::Option<String>,
    pub scope: String,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub updated_at: core::option::Option<crate::types::string::Datetime>,
    pub value: crate::types::Unknown,
}
pub type Option = crate::types::Object<OptionData>;
