// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `app.bsky.feed.defs` namespace.

/// `app.bsky.feed.defs#feedViewPost`
pub struct FeedViewPost {}

/// `app.bsky.feed.defs#notFoundPost`
pub struct NotFoundPost {}

/// `app.bsky.feed.defs#postView`
pub struct PostView {}

/// `app.bsky.feed.defs#reasonRepost`
pub struct ReasonRepost {}

/// `app.bsky.feed.defs#replyRef`
pub struct ReplyRef {}

/// `app.bsky.feed.defs#threadViewPost`
pub struct ThreadViewPost {}

/// `app.bsky.feed.defs#viewerState`
pub struct ViewerState {}
