// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.feed.defs` namespace.

// app.bsky.feed.defs#feedViewPost
pub struct FeedViewPost {
    // pub post: ...
    // pub reason: ...,
    // pub reply: ...
}

// app.bsky.feed.defs#notFoundPost
pub struct NotFoundPost {
    pub not_found: bool,
    pub uri: String,
}

// app.bsky.feed.defs#postView
pub struct PostView {
    // pub author: ...
    pub cid: String,
    // pub embed: ...,
    pub indexed_at: String,
    // pub labels: ...,
    pub like_count: Option<i32>,
    // pub record: ...,
    pub reply_count: Option<i32>,
    pub repost_count: Option<i32>,
    pub uri: String,
    // pub viewer: ...
}

// app.bsky.feed.defs#reasonRepost
pub struct ReasonRepost {
    // pub by: ...
    pub indexed_at: String,
}

// app.bsky.feed.defs#replyRef
pub struct ReplyRef {
    // pub parent: ...
    // pub root: ...
}

// app.bsky.feed.defs#threadViewPost
pub struct ThreadViewPost {
    // pub parent: ...,
    // pub post: ...
    // pub replies: ...,
}

// app.bsky.feed.defs#viewerState
pub struct ViewerState {
    pub like: Option<String>,
    pub repost: Option<String>,
}
