// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.feed.getRepostedBy` namespace.

pub trait GetRepostedBy {
    fn get_reposted_by(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    pub cid: Option<String>,
    pub cursor: Option<String>,
    pub limit: Option<i32>,
    pub uri: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub cid: Option<String>,
    pub cursor: Option<String>,
    pub reposted_by: Vec<crate::app::bsky::actor::defs::ProfileView>,
    pub uri: String,
}

pub enum Error {
}
