// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.feed.getTimeline` namespace.

/// A view of the user's home timeline.
#[async_trait::async_trait]
pub trait GetTimeline: crate::xrpc::XrpcClient {
    async fn get_timeline(&self, params: Parameters) -> Result<Output, Box<dyn std::error::Error>> {
        crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "app.bsky.feed.getTimeline",
            Some(params),
            Option::<()>::None,
        )
        .await
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    pub algorithm: Option<String>,
    pub cursor: Option<String>,
    pub limit: Option<i32>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub cursor: Option<String>,
    pub feed: Vec<crate::app::bsky::feed::defs::FeedViewPost>,
}

pub enum Error {
}
