// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.feed.getPosts` namespace.

/// A view of an actor's feed.
pub trait GetPosts {
    fn get_posts(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    pub uris: Vec<String>,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Output {
    pub posts: Vec<crate::app::bsky::feed::defs::PostView>,
}

pub enum Error {
}
