// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.feed.post` namespace.

// app.bsky.feed.post
pub struct Main {}

// app.bsky.feed.post#entity
/// Deprecated: use facets instead.
pub struct Entity {
    pub index: TextSlice,
    /// Expected values are 'mention' and 'link'.
    pub r#type: String,
    pub value: String,
}

// app.bsky.feed.post#replyRef
pub struct ReplyRef {
    pub parent: crate::com::atproto::repo::strong_ref::Main,
    pub root: crate::com::atproto::repo::strong_ref::Main,
}

// app.bsky.feed.post#textSlice
/// Deprecated. Use app.bsky.richtext instead -- A text segment. Start is inclusive, end is exclusive. Indices are for utf16-encoded strings.
pub struct TextSlice {
    pub end: i32,
    pub start: i32,
}
