// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `com.atproto.moderation.defs` namespace.

/// `com.atproto.moderation.defs#reasonMisleading`
pub struct ReasonMisleading {}

/// `com.atproto.moderation.defs#reasonOther`
pub struct ReasonOther {}

/// `com.atproto.moderation.defs#reasonRude`
pub struct ReasonRude {}

/// `com.atproto.moderation.defs#reasonSexual`
pub struct ReasonSexual {}

/// `com.atproto.moderation.defs#reasonSpam`
pub struct ReasonSpam {}

/// `com.atproto.moderation.defs#reasonType`
pub struct ReasonType {}

/// `com.atproto.moderation.defs#reasonViolation`
pub struct ReasonViolation {}
