// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `app.bsky.richtext.facet` namespace.

// app.bsky.richtext.facet
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Main {
    pub features: Vec<MainFeaturesItem>,
    pub index: ByteSlice,
}

// app.bsky.richtext.facet#byteSlice
/// A text segment. Start is inclusive, end is exclusive. Indices are for utf8-encoded strings.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ByteSlice {
    pub byte_end: i32,
    pub byte_start: i32,
}

// app.bsky.richtext.facet#link
/// A facet feature for links.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Link {
    pub uri: String,
}

// app.bsky.richtext.facet#mention
/// A facet feature for actor mentions.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Mention {
    pub did: String,
}

#[allow(clippy::large_enum_variant)]
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum MainFeaturesItem {
    #[serde(rename = "app.bsky.richtext.facet#mention")]
    Mention(Mention),
    #[serde(rename = "app.bsky.richtext.facet#link")]
    Link(Link),
}
