// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.actor.getProfile` namespace.
pub const NSID: &str = "app.bsky.actor.getProfile";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Handle or DID of account to fetch profile of.
    pub actor: crate::types::string::AtIdentifier,
}
pub type Parameters = crate::types::Object<ParametersData>;
pub type Output = crate::app::bsky::actor::defs::ProfileViewDetailed;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
