// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.communication` namespace.
pub mod create_template;
pub mod defs;
pub mod delete_template;
pub mod list_templates;
pub mod update_template;
