// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.setting` namespace.
pub mod defs;
pub mod list_options;
pub mod remove_options;
pub mod upsert_option;
