// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.label.subscribeLabels` namespace.

// com.atproto.label.subscribeLabels
// TODO

// com.atproto.label.subscribeLabels#info
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Info {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    pub name: String,
}

// com.atproto.label.subscribeLabels#labels
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Labels {
    pub labels: Vec<crate::com::atproto::label::defs::Label>,
    pub seq: i32,
}
