// This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.server.deactivateAccount` namespace.
pub const NSID: &str = "com.atproto.server.deactivateAccount";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    ///A recommendation to server as to how long they should hold onto the deactivated account before deleting.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub delete_after: Option<crate::types::string::Datetime>,
    #[serde(flatten)]
    pub extra_data: ipld_core::ipld::Ipld,
}
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
