// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.server.getAccountInviteCodes` namespace.

/// Get all invite codes for a given account
#[async_trait::async_trait]
pub trait GetAccountInviteCodes: crate::xrpc::XrpcClient {
    async fn get_account_invite_codes(&self, params: Parameters) -> Result<Output, Box<dyn std::error::Error>> {
        crate::xrpc::XrpcClient::send(
            self,
            http::Method::GET,
            "com.atproto.server.getAccountInviteCodes",
            Some(params),
            Option::<()>::None,
        )
        .await
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Parameters {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub create_available: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_used: Option<bool>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub codes: Vec<crate::com::atproto::server::defs::InviteCode>,
}

pub enum Error {
    DuplicateCreate,
}
