// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.server.refreshSession` namespace.

/// Refresh an authentication session.
#[async_trait::async_trait]
pub trait RefreshSession: crate::xrpc::XrpcClient {
    async fn refresh_session(&self, input: Vec<u8>) -> Result<Output, Box<dyn std::error::Error>> {
        let body = crate::xrpc::XrpcClient::send::<Error>(
            self,
            http::Method::POST,
            "com.atproto.server.refreshSession",
            None,
            Some(input),
            None,
        )
        .await?;
        serde_json::from_slice(&body).map_err(|e| e.into())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub access_jwt: String,
    pub did: String,
    pub handle: String,
    pub refresh_jwt: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {
    AccountTakedown(Option<String>),
}
