// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.server.requestAccountDelete` namespace.

/// Initiate a user account deletion via email.
#[async_trait::async_trait]
pub trait RequestAccountDelete: crate::xrpc::XrpcClient {
    async fn request_account_delete(&self, input: Vec<u8>) -> Result<(), Box<dyn std::error::Error>> {
        let _ = crate::xrpc::XrpcClient::send(
            self,
            http::Method::POST,
            "com.atproto.server.requestAccountDelete",
            None,
            Some(input),
            None,
        )
        .await?;
        Ok(())
    }
}

pub enum Error {
}
