// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.server.resetPassword` namespace.

/// Reset a user account password using a token.
#[async_trait::async_trait]
pub trait ResetPassword: crate::xrpc::XrpcClient {
    async fn reset_password(&self, input: Input) -> Result<(), Box<dyn std::error::Error>> {
        let _ = crate::xrpc::XrpcClient::send(
            self,
            http::Method::POST,
            "com.atproto.server.resetPassword",
            None,
            Some(serde_json::to_vec(&input)?),
            Some(String::from("application/json")),
        )
        .await?;
        Ok(())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    pub password: String,
    pub token: String,
}

pub enum Error {
    ExpiredToken,
    InvalidToken,
}
