// This file is generated by atrium-codegen. Do not edit.
//! Definitions for the `com.atproto.server.revokeAppPassword` namespace.

/// Revoke an app-specific password by name.
#[async_trait::async_trait]
pub trait RevokeAppPassword: crate::xrpc::XrpcClient {
    async fn revoke_app_password(&self, input: Input) -> Result<(), Box<dyn std::error::Error>> {
        let _ = crate::xrpc::XrpcClient::send::<Error>(
            self,
            http::Method::POST,
            "com.atproto.server.revokeAppPassword",
            None,
            Some(serde_json::to_vec(&input)?),
            Some(String::from("application/json")),
        )
        .await?;
        Ok(())
    }
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Input {
    pub name: String,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
