// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.server.createAccount` namespace.

/// Create an account.
pub trait CreateAccount {
    fn create_account(&self, input: Input) -> Result<Output, Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub email: String,
    pub handle: String,
    pub invite_code: Option<String>,
    pub password: String,
    pub recovery_key: Option<String>,
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Output {
    pub access_jwt: String,
    pub did: String,
    pub handle: String,
    pub refresh_jwt: String,
}

pub enum Error {
    InvalidHandle,
    InvalidPassword,
    InvalidInviteCode,
    HandleNotAvailable,
    UnsupportedDomain,
}
