// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `com.atproto.server.defs` namespace.

/// `com.atproto.server.defs#inviteCode`
pub struct InviteCode {}

/// `com.atproto.server.defs#inviteCodeUse`
pub struct InviteCodeUse {}
