// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.server.defs` namespace.

// com.atproto.server.defs#inviteCode
pub struct InviteCode {
    pub available: i32,
    pub code: String,
    pub created_at: String,
    pub created_by: String,
    pub disabled: bool,
    pub for_account: String,
    pub uses: Vec<InviteCodeUse>,
}

// com.atproto.server.defs#inviteCodeUse
pub struct InviteCodeUse {
    pub used_at: String,
    pub used_by: String,
}
