// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.server.deleteAccount` namespace.

/// Delete a user account with a token and password.
pub trait DeleteAccount {
    fn delete_account(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub did: String,
    pub password: String,
    pub token: String,
}

pub enum Error {
    ExpiredToken,
    InvalidToken,
}
