// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `com.atproto.server.describeServer` namespace.

// TODO

/// `com.atproto.server.describeServer#links`
pub struct Links {}
