// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `com.atproto.server.listAppPasswords` namespace.

// TODO

/// `com.atproto.server.listAppPasswords#appPassword`
pub struct AppPassword {}
