// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `com.atproto.server.refreshSession` namespace.

/// Refresh an authentication session.
pub trait RefreshSession {
    fn refresh_session(&self) -> Result<Output, Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Output {
    pub access_jwt: String,
    pub did: String,
    pub handle: String,
    pub refresh_jwt: String,
}

pub enum Error {
    AccountTakedown,
}
