// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.embed.record` namespace.

// app.bsky.embed.record
pub struct Main {
    pub record: crate::com::atproto::repo::strong_ref::Main,
}

// app.bsky.embed.record#view
pub struct View {
    // pub record: ...,
}

// app.bsky.embed.record#viewNotFound
pub struct ViewNotFound {
    pub uri: String,
}

// app.bsky.embed.record#viewRecord
pub struct ViewRecord {
    pub author: crate::app::bsky::actor::defs::ProfileViewBasic,
    pub cid: String,
    // pub embeds: Vec<...>
    pub indexed_at: String,
    pub uri: String,
    // pub value: ...,
}
