// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.embed.recordWithMedia` namespace.

// app.bsky.embed.recordWithMedia
#[derive(serde::Serialize, serde::Deserialize)]
pub struct Main {
    // pub media: ...,
    pub record: crate::app::bsky::embed::record::Main,
}

// app.bsky.embed.recordWithMedia#view
#[derive(serde::Serialize, serde::Deserialize)]
pub struct View {
    // pub media: ...,
    pub record: crate::app::bsky::embed::record::View,
}
