// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.embed.recordWithMedia` namespace.
//! A representation of a record embedded in another form of content, alongside other compatible embeds

// app.bsky.embed.recordWithMedia
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Main {
    // pub media: ...,
    pub record: crate::app::bsky::embed::record::Main,
}

// app.bsky.embed.recordWithMedia#view
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct View {
    // pub media: ...,
    pub record: crate::app::bsky::embed::record::View,
}
