// This file is generated by atprs-codegen. Do not edit
//! Definitions for the `app.bsky.embed.record` namespace.

/// `app.bsky.embed.record`
pub struct Main {}

/// `app.bsky.embed.record#view`
pub struct View {}

/// `app.bsky.embed.record#viewNotFound`
pub struct ViewNotFound {}

/// `app.bsky.embed.record#viewRecord`
pub struct ViewRecord {}
