// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.lexicon.schema` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Indicates the 'version' of the Lexicon language. Must be '1' for the current atproto/Lexicon schema system.
    pub lexicon: i64,
}
pub type Record = crate::types::Object<RecordData>;
