// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.identity.defs` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct IdentityInfoData {
    pub did: crate::types::string::Did,
    ///The complete DID document for the identity.
    pub did_doc: crate::types::Unknown,
    ///The validated handle of the account; or 'handle.invalid' if the handle did not bi-directionally match the DID document.
    pub handle: crate::types::string::Handle,
}
pub type IdentityInfo = crate::types::Object<IdentityInfoData>;
