// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.set.upsertSet` namespace.
pub const NSID: &str = "tools.ozone.set.upsertSet";
pub type Input = crate::tools::ozone::set::defs::Set;
pub type Output = crate::tools::ozone::set::defs::SetView;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
