// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.graph.getFollows` namespace.

/// Who is an actor following?
pub trait GetFollows {
    fn get_follows(&self, input: Parameters) -> Result<Output, Error>;
}

pub struct Parameters {
    pub actor: String,
    pub cursor: Option<String>,
    pub limit: Option<i32>,
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Output {
    pub cursor: Option<String>,
    pub follows: Vec<crate::app::bsky::actor::defs::ProfileView>,
    pub subject: crate::app::bsky::actor::defs::ProfileView,
}

pub enum Error {
}
