// This file is generated by atprs-codegen. Do not edit.
//! Definitions for the `app.bsky.graph.muteActor` namespace.

/// Mute an actor by did or handle.
pub trait MuteActor {
    fn mute_actor(&self, input: Input) -> Result<(), Error>;
}

#[derive(serde::Serialize, serde::Deserialize)]
pub struct Input {
    pub actor: String,
}

pub enum Error {
}
