// This file is generated by atrium-codegen. DO NOT EDIT.
#![doc = "Definitions for the `com.atproto.moderation.defs` namespace."]
#[doc = "Misleading identity, affiliation, or content"]
pub struct ReasonMisleading;
#[doc = "Other: reports not falling under another report category"]
pub struct ReasonOther;
#[doc = "Rude, harassing, explicit, or otherwise unwelcoming behavior"]
pub struct ReasonRude;
#[doc = "Unwanted or mislabeled sexual content"]
pub struct ReasonSexual;
#[doc = "Spam: frequent unwanted promotion, replies, mentions"]
pub struct ReasonSpam;
pub type ReasonType = String;
#[doc = "Direct violation of server rules, laws, terms of service"]
pub struct ReasonViolation;
